export default [
  {
    "adult": false,
    "backdrop_path": "/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
    "genre_ids": [28, 12, 878],
    "id": 634649,
    "original_language": "en",
    "original_title": "Spider-Man: No Way Home",
    "overview": "Peter Parker es desenmascarado y por tanto no es capaz de separar su vida normal de los enormes riesgos que conlleva ser un súper héroe. Cuando pide ayuda a Doctor Strange, los riesgos pasan a ser aún más peligrosos, obligándole a descubrir lo que realmente significa ser Spider-Man.",
    "popularity": 5342.778,
    "poster_path": "/osYbtvqjMUhEXgkuFJOsRYVpq6N.jpg",
    "release_date": "2021-12-15",
    "title": "Spider-Man: No Way Home",
    "video": false,
    "vote_average": 8.3,
    "vote_count": 8670
  },
  {
    "adult": false,
    "backdrop_path": "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
    "genre_ids": [16, 35, 10751, 14],
    "id": 568124,
    "original_language": "en",
    "original_title": "Encanto",
    "overview": "\"Encanto\" relata la historia de los Madrigal, una familia extraordinaria que vive en una casa mágica de un pueblo vibrante en las montañas de Colombia escondidas en un “Encanto”. La magia del Encanto ha bendecido a cada niño de la familia con un don único, desde la superfuerza hasta el poder de sanar. A todos, excepto Mirabel, quien desea ser tan especial como el resto de su familia.  Pero cuando la magia que rodea al Encanto está en peligro, Mirabel decide que ella, la única Madrigal sin ningún tipo de don único, puede ser la única esperanza de su excepcional familia.",
    "popularity": 2437.333,
    "poster_path": "/d0ezQ1Jz0lpNsX1skEmIvqRL7mN.jpg",
    "release_date": "2021-11-24",
    "title": "Encanto",
    "video": false,
    "vote_average": 7.7,
    "vote_count": 4915
  },
  {
    "adult": false,
    "backdrop_path": "/5P8SmMzSNYikXpxil6BYzJ16611.jpg",
    "genre_ids": [28, 80, 18],
    "id": 414906,
    "original_language": "en",
    "original_title": "The Batman",
    "overview": "Cuando un asesino se dirige a la élite de Gotham con una serie de maquinaciones sádicas, un rastro de pistas crípticas envía Batman a una investigación en los bajos fondos. A medida que las pruebas comienzan a acercarse a su casa y se hace evidente la magnitud de los planes del autor, Batman debe forjar nuevas relaciones, desenmascarar al culpable y hacer justicia al abuso de poder y la corrupción que durante mucho tiempo han asolado Gotham City.",
    "popularity": 2346.043,
    "poster_path": "/pOaKyhMwALpCTg07eQQu0SQCbL9.jpg",
    "release_date": "2022-03-01",
    "title": "The Batman",
    "video": false,
    "vote_average": 8.2,
    "vote_count": 281
  },
  {
    "adult": false,
    "backdrop_path": "/4OTYefcAlaShn6TGVK33UxLW9R7.jpg",
    "genre_ids": [28, 12, 53, 10752],
    "id": 476669,
    "original_language": "en",
    "original_title": "The King's Man",
    "overview": "Cuando un grupo formado por los tiranos y las mentes criminales más malvadas de la historia se une para desencadenar una guerra que matará a millones de personas, un hombre tendrá que luchar a contrarreloj para detenerlos. Tercera entrega de la saga 'Kingsman', ambientada muchos años antes de las anteriores y explicando el origen de la agencia.",
    "popularity": 2094.307,
    "poster_path": "/lFu7pTdf4gXABogCmPE0cBkVQZu.jpg",
    "release_date": "2021-12-22",
    "title": "The King's Man: La primera misión",
    "video": false,
    "vote_average": 7.1,
    "vote_count": 1650
  },
  {
    "adult": false,
    "backdrop_path": "/usaZV7KB6Man9Rm9TyDAeQf7uVD.jpg",
    "genre_ids": [27, 9648, 53],
    "id": 646385,
    "original_language": "en",
    "original_title": "Scream",
    "overview": "Una nueva entrega de la saga de terror 'Scream' que seguirá a una mujer que regresa a su ciudad natal para intentar descubrir quién ha estado cometiendo una serie de crímenes atroces.",
    "popularity": 1908.323,
    "poster_path": "/cIgmdAhesIqn2ykJfbNFMQYdxkO.jpg",
    "release_date": "2022-01-12",
    "title": "Scream",
    "video": false,
    "vote_average": 6.9,
    "vote_count": 761
  },
  {
    "adult": false,
    "backdrop_path": "/mruT954ve6P1zquaRs6XG0hA5k9.jpg",
    "genre_ids": [53],
    "id": 800510,
    "original_language": "en",
    "original_title": "Kimi",
    "overview": "Durante la pandemia de COVID-19 en Seattle, una trabajadora tecnológica agorafóbica descubre evidencia de un crimen violento mientras revisa un flujo de datos, y se encuentra con resistencia y burocracia cuando intenta informarlo a su empresa. Para involucrarse, se da cuenta de que debe enfrentar su mayor miedo y aventurarse a salir de su apartamento y adentrarse en las calles de la ciudad, que están llenas de manifestantes luego de que el ayuntamiento aprobara una ley que restringe los movimientos de la población sin hogar.",
    "popularity": 1841.279,
    "poster_path": "/okNgwtxIWzGsNlR3GsOS0i0Qgbn.jpg",
    "release_date": "2022-02-10",
    "title": "Kimi",
    "video": false,
    "vote_average": 6.3,
    "vote_count": 175
  },
  {
    "adult": false,
    "backdrop_path": "/wMUPT99gw6IB9OVvC46rF8wHIRt.jpg",
    "genre_ids": [28, 80, 14],
    "id": 890656,
    "original_language": "en",
    "original_title": "Fistful of Vengeance",
    "overview": "Kai Jin, un joven chef de Chinatown en la actual San Francisco, se ve envuelto en la búsqueda de la Tríada China de poderes ancestrales mortales conocidos como el \"Wu Xing\".",
    "popularity": 1839.623,
    "poster_path": "/1pOdSYjmnX61Nh9sMyztwnPJe98.jpg",
    "release_date": "2022-02-17",
    "title": "Venganza a golpes",
    "video": false,
    "vote_average": 5.4,
    "vote_count": 97
  },
  {
    "adult": false,
    "backdrop_path": "/eG0oOQVsniPAuecPzDD1B1gnYWy.jpg",
    "genre_ids": [16, 35, 12, 10751],
    "id": 774825,
    "original_language": "en",
    "original_title": "The Ice Age Adventures of Buck Wild",
    "overview": "Continúa contando las hilarantes aventuras de uno de los mamíferos favoritos de la prehistoria. Tras un distanciamiento con su hermana mayor, Ellie, los hermanos Crash y Eddie parten a la búsqueda de un lugar propio, pero rápidamente acaban atrapados en una caverna subterránea. El aventurero Buck Wild acudirá a su rescate y juntos, tendrán que enfrentarse a los dinosaurios del Mundo Perdido.",
    "popularity": 1763.799,
    "poster_path": "/iDah4ZcDX3F316LcLlmNNAzsRqF.jpg",
    "release_date": "2022-01-28",
    "title": "Ice Age: Las aventuras de Buck",
    "video": false,
    "vote_average": 7.2,
    "vote_count": 684
  },
  {
    "adult": false,
    "backdrop_path": "/cugmVwK0N4aAcLibelKN5jWDXSx.jpg",
    "genre_ids": [16, 28, 14, 12],
    "id": 768744,
    "original_language": "ja",
    "original_title": "僕のヒーローアカデミア THE MOVIE ワールド ヒーローズ ミッション",
    "overview": "Deku es perseguido por la policía, acusado de asesinato en masa, mientras que el resto de super héroes han de enfrentarse a un incidente que afecta a todo el mundo. Tercera película de la serie anime \"My Hero Academia\".",
    "popularity": 1625.709,
    "poster_path": "/aj46sbSKF8ek0cLBW1En921NXWu.jpg",
    "release_date": "2021-08-06",
    "title": "My Hero Academia: Misión mundial de héroes",
    "video": false,
    "vote_average": 7.4,
    "vote_count": 88
  },
  {
    "adult": false,
    "backdrop_path": "/aTSA5zMWlVFTYBIZxTCMbLkfOtb.jpg",
    "genre_ids": [27],
    "id": 632727,
    "original_language": "en",
    "original_title": "Texas Chainsaw Massacre",
    "overview": "Melody (Sarah Yarkin), su hermana adolescente Lila (Elsie Fisher) y sus amigos Dante (Jacob Latimore) y Ruth (Nell Hudson) viajan al remoto pueblo de Harlow (Texas) para montar un negocio muy idealista. Pero su sueño se convierte en una auténtica pesadilla cuando molestan sin querer a Leatherface, el desquiciado asesino en serie cuyo sangriento legado sigue acechando a los habitantes de la zona, entre ellos Sally Hardesty (Olwen Fouéré), la única superviviente de su masacre de 1973, decidida a vengarse a muerte.",
    "popularity": 1605.691,
    "poster_path": "/2VnuxwgdMBEgVO7VKvkW6nmYfaM.jpg",
    "release_date": "2022-02-18",
    "title": "La Matanza de Texas",
    "video": false,
    "vote_average": 5.1,
    "vote_count": 471
  },
  {
    "adult": false,
    "backdrop_path": "/mqDnDhG5N6fn1H4MKQqr8E5wfeK.jpg",
    "genre_ids": [80, 18, 53],
    "id": 597208,
    "original_language": "en",
    "original_title": "Nightmare Alley",
    "overview": "Un buscavidas se compincha con una pitonisa para engañar a la gente y conseguir dinero... Remake del film \"El callejón de las almas perdidas\" (Nightmare Alley) de 1947.",
    "popularity": 1488.075,
    "poster_path": "/vH5rh852MByFzEwEIQ7Us7dJhy1.jpg",
    "release_date": "2021-12-02",
    "title": "El callejón de las almas perdidas",
    "video": false,
    "vote_average": 7.1,
    "vote_count": 910
  },
  {
    "adult": false,
    "backdrop_path": "/c6H7Z4u73ir3cIoCteuhJh7UCAR.jpg",
    "genre_ids": [28, 12, 14, 878],
    "id": 524434,
    "original_language": "en",
    "original_title": "Eternals",
    "overview": "Hace millones de años, los seres cósmicos conocidos como los Celestiales comenzaron a experimentar genéticamente con los humanos. Su intención era crear individuos superpoderosos que hicieran únicamente el bien, pero algo salió mal y aparecieron los Desviantes, destruyendo y creando el caos a su paso. Ambas razas se han enfrentado en una eterna lucha de poder a lo largo de la historia. En medio de esta guerra, Ikaris y Sersi tratarán de vivir su propia historia de amor.",
    "popularity": 1483.559,
    "poster_path": "/wPZ5n5LlzFFdO5lFJbi2qmaE6w7.jpg",
    "release_date": "2021-11-03",
    "title": "Eternals",
    "video": false,
    "vote_average": 7.2,
    "vote_count": 4627
  },
  {
    "adult": false,
    "backdrop_path": "/dK12GIdhGP6NPGFssK2Fh265jyr.jpg",
    "genre_ids": [28, 35, 80, 53],
    "id": 512195,
    "original_language": "en",
    "original_title": "Red Notice",
    "overview": "Cuando la Interpol envía una \"Alerta roja\", significa que los departamentos de Policía de todo el mundo deben estar alerta para capturar a los criminales más buscados. Todas las alarmas saltan cuando un temerario robo une al mejor agente del FBI (Johnson) con dos criminales rivales entre sí (Gadot & Reynolds). Una coincidencia que hará que suceda lo impredecible.",
    "popularity": 1461.898,
    "poster_path": "/odBUpjZGxY3y7FBo5NBtEYGJf5r.jpg",
    "release_date": "2021-11-04",
    "title": "Alerta roja",
    "video": false,
    "vote_average": 6.8,
    "vote_count": 3156
  },
  {
    "adult": false,
    "backdrop_path": "/qBLEWvJNVsehJkEJqIigPsWyBse.jpg",
    "genre_ids": [16, 10751, 14, 35, 12],
    "id": 585083,
    "original_language": "en",
    "original_title": "Hotel Transylvania: Transformania",
    "overview": "Drac y la pandilla vuelven, como nunca los habías visto antes en Hotel Transilvania: Transformanía. Volveremos a encontrarnos con nuestros monstruos favoritos en una aventura completamente nueva en la que Drac se enfrentará a una de las situaciones más aterradoras vividas hasta el momento. Cuando el misterioso invento de Van Helsing, el \"Rayo Monstrificador\", se vuelve totalmente fuera de control, Drac y sus monstruosos amigos se transforman en humanos, ¡y Johnny se convierte en un monstruo!",
    "popularity": 1460.032,
    "poster_path": "/pwSlzCAynIF6aEP7oxWddo7Kng2.jpg",
    "release_date": "2022-02-25",
    "title": "Hotel Transilvania: Transformanía",
    "video": false,
    "vote_average": 7,
    "vote_count": 217
  },
  {
    "adult": false,
    "backdrop_path": "/eVSa4TpyXbOdk9fXSD6OcORJGtv.jpg",
    "genre_ids": [53],
    "id": 803114,
    "original_language": "en",
    "original_title": "The Requin",
    "overview": "Una pareja de escapada romántica se encuentra en el mar cuando una tormenta tropical arrasa su villa. Para sobrevivir se ven obligados a luchar contra los elementos mientras los tiburones les rodean.",
    "popularity": 1356.2,
    "poster_path": "/i0z8g2VRZP3dhVvvSMilbOZMKqR.jpg",
    "release_date": "2022-01-28",
    "title": "Sharkwater",
    "video": false,
    "vote_average": 4.7,
    "vote_count": 59
  },
  {
    "adult": false,
    "backdrop_path": "/kQM7o3NIkruIZLoQ9E2XzZQ8Ujl.jpg",
    "genre_ids": [28, 35, 80],
    "id": 783461,
    "original_language": "hi",
    "original_title": "लूप लपेटा",
    "overview": "Cuando su novio pierde el dinero de un mafioso, Savi corre para salvar la situación. Pero solo tendrá éxito si logra salir de una extraña serie de acontecimientos.",
    "popularity": 1202.869,
    "poster_path": "/k18NeY5DlJupyTbqmJOV0oYHLfS.jpg",
    "release_date": "2022-02-04",
    "title": "Un bucle sin fin",
    "video": false,
    "vote_average": 6,
    "vote_count": 23
  },
  {
    "adult": false,
    "backdrop_path": "/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg",
    "genre_ids": [35, 16, 10751, 10402],
    "id": 438695,
    "original_language": "en",
    "original_title": "Sing 2",
    "overview": "Buster Moon y sus amigos deben persuadir a la estrella del rock Clay Calloway para que se una a ellos en el estreno de un nuevo espectáculo.",
    "popularity": 1151.199,
    "poster_path": "/gR2o0LBWq32oGdIVqeIloO3KDxY.jpg",
    "release_date": "2021-12-01",
    "title": "¡Canta! 2",
    "video": false,
    "vote_average": 8.2,
    "vote_count": 2089
  },
  {
    "adult": false,
    "backdrop_path": "/xHRabofjmMGoIV3mb6xgy4nwOcS.jpg",
    "genre_ids": [27],
    "id": 801071,
    "original_language": "en",
    "original_title": "The Jack in the Box: Awakening",
    "overview": "Cuando una mujer moribunda abre un Jack-in-the-box antiguo, entra en un trato con el demonio interno que curaría su enfermedad a cambio de ayudarla a reclamar seis víctimas inocentes.",
    "popularity": 1064.47,
    "poster_path": "/3Ib8vlWTrAKRrTWUrTrZPOMW4jp.jpg",
    "release_date": "2022-01-03",
    "title": "The Jack in the Box: Awakening",
    "video": false,
    "vote_average": 5.6,
    "vote_count": 39
  },
  {
    "adult": false,
    "backdrop_path": "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
    "genre_ids": [878, 28, 12],
    "id": 580489,
    "original_language": "en",
    "original_title": "Venom: Let There Be Carnage",
    "overview": "Eddie Brock  y su simbionte Venom todavía están intentando descubrir cómo vivir juntos cuando un preso que está en el corredor de la muerte se infecta con un simbionte propio.",
    "popularity": 1046.771,
    "poster_path": "/b0j9rHYpRML7dKm5xw9e97HTDJF.jpg",
    "release_date": "2021-09-30",
    "title": "Venom: Habrá Matanza",
    "video": false,
    "vote_average": 7.1,
    "vote_count": 6478
  },
  {
    "adult": false,
    "backdrop_path": "/t4To8feUSysyBs4tlBAbXIrKlCv.jpg",
    "genre_ids": [28, 53],
    "id": 860623,
    "original_language": "en",
    "original_title": "Last Man Down",
    "overview": "Después de que la civilización sucumbe a una pandemia mortal y su esposa es asesinada, un soldado de las fuerzas especiales abandona su deber y se convierte en un ermitaño en el desierto nórdico. Años más tarde, una mujer herida aparece en su puerta. Ella escapó de un laboratorio y sus perseguidores creen que su sangre es la clave para una cura mundial. Él duda en involucrarse, pero todas las dudas se hacen a un lado cuando descubre que su perseguidor no es otro que el Comandante Stone, el hombre que asesinó a su esposa hace algunos años.",
    "popularity": 1024.051,
    "poster_path": "/bWifGZF9fkJ83zOVHPGaN4ZL2pQ.jpg",
    "release_date": "2021-10-19",
    "title": "El último superviviente",
    "video": false,
    "vote_average": 6.3,
    "vote_count": 300
  }
]
